# Generated by Django 4.1.3 on 2022-12-15 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('promotion_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inventory_number', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image_product', models.ImageField(blank=True, null=True, upload_to='uploads/products')),
                ('favorite', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category')),
            ],
        ),
    ]
