# Generated by Django 4.1.3 on 2023-01-06 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='minimum_amount',
        ),
    ]
