# Generated by Django 4.1.3 on 2022-12-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_field',
            field=models.TextField(blank=True, null=True, verbose_name='Pesquisar'),
        ),
    ]
