# Generated by Django 4.1.3 on 2022-12-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_search_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
