# Generated by Django 4.1.3 on 2022-12-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_promotion_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_product',
        ),
    ]
