# Generated by Django 4.0.4 on 2022-12-14 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=255, null=True)),
                ('order_status', models.IntegerField(choices=[(0, 'Pagamento não finalizado'), (1, 'Pagamento autorizado'), (2, 'Pagamento confirmado'), (3, 'Pagamento negado'), (10, 'Pagamento cancelado'), (11, 'Devolvido'), (12, 'Pendente'), (13, 'Abortado'), (20, 'Agendado'), (21, 'Enviado'), (22, 'Recebido'), (30, 'Gerando nota fiscal'), (31, 'Enviado'), (32, 'Entregue')], default=12, verbose_name='Status do pedido')),
                ('payment_type', models.IntegerField(choices=[(1, 'Boleto'), (2, 'Cartão de crédito'), (3, 'Cartão de débito'), (4, 'Pix')], default=1, verbose_name='Tipo')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='uploads/receipts', verbose_name='Nota Fiscal')),
                ('total_amount_products', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total produtos')),
                ('total_amount_discount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total desconto')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clients.client', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
