# Generated by Django 4.1.3 on 2022-12-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount_discount',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Dinheiro'), (2, 'Cartão de crédito'), (3, 'Cartão de débito'), (4, 'Pix')], default=1, verbose_name='Tipo'),
        ),
    ]
