# Generated by Django 4.1.3 on 2022-12-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='frete_type',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='has_frete',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='pac_prazo',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='pac_value',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sedex_prazo',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sedex_value',
        ),
        migrations.AddField(
            model_name='cart',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Pix'), (2, 'Cartão de Débito'), (3, 'Cartão de Crédito'), (4, 'Dinheiro')], default=1),
        ),
    ]
