# Generated by Django 4.1.3 on 2022-12-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
