# Generated by Django 4.1.3 on 2022-11-27 13:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_procuct', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=100, max_digits=12)),
                ('promotion_price', models.DecimalField(decimal_places=2, default=100, max_digits=12)),
                ('inventory_number', models.DecimalField(decimal_places=2, default=100, max_digits=12)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=100, max_digits=12)),
                ('image_product', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
