# Generated by Django 4.0.4 on 2022-12-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
