# Generated by Django 4.0.4 on 2022-12-01 14:14

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_product',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_product),
        ),
    ]
