# Generated by Django 4.0.4 on 2022-12-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_image_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='id_procuct',
            new_name='id_product',
        ),
    ]
